### ISSUE TITLE
Display of "|" pipe Symbol in sender name

### ISSUE THREAD

**Issue by bpcurse** [JojiiOfficial/Matrix-EmailBridge#26]
EmailBridge doesn't correctly display email sender names if they contain the "|" pipe symbol as in "John Doe | Some Company Name". 
Instead it displays `"You've got a new Email from =?utf-8?b?longstringofasciicharacters=?="`

It is displayed correctly if used in the email's subject.

**Comment by JojiiOfficial** [comment]
Interesting. I'll have a look at it.
