### ISSUE TITLE
name of bridge

### ISSUE THREAD

**Issue by bendschs** [JojiiOfficial/Matrix-EmailBridge#35]
I can not figure out the name of to bridge to invite. 

it starts correctly with 
```
./emailbridge 
logged into matrix successfully
```

do i have to register a new user for the bridge?

**Comment by JojiiOfficial** [comment]
You have to register a new user on your home server. You have to add this user to the config file. Then you start the bridge and invite this user into a private room.

**Comment by bendschs** [comment]
ok did that, the user is invited end online but does not seem to reply.
what is wrong here?

<img width="1159" alt="Bildschirmfoto 2021-01-17 um 13 04 38" src="https://user-images.githubusercontent.com/17085451/104839914-9ca7a980-58c4-11eb-80be-473a57741bc1.png">

**Comment by bendschs** [comment]
i actually noticed, that the bridge gives a successful login message even when it is started with fresh config file, so that is a bot missleading.
```
./emailbridge 
logged into matrix successfully
@m:matrix.org
```

**Comment by bendschs** [comment]
so since i have no possibility to check if the configuration is right, i am posting my config file here (actual domain and token edited out). Can anybody tell me if it looks right?
```
{
  "allowed_servers": [
    "matrix.myserver.com,"
  ],
  "defaultmailcheckinterval": 30,
  "htmldefault": false,
  "markdownenabledbydefault": true,
  "matrixaccesstoken": „mytoken",
  "matrixserver": "matrix.myserver.com",
  "matrixuserid": "@emailbot:matrix.myserver.com"
}
```

**Comment by JojiiOfficial** [comment]
Your config looks fine. This issue is very likely related to #36

**Comment by JojiiOfficial** [comment]
#38 should've fixed this issue. On further issues, reopen this one or create a new one.
