### ISSUE TITLE
EmailBridge not working with recent version of matrix server (synapse)

### ISSUE THREAD

**Issue by JonathanReifer** [JojiiOfficial/Matrix-EmailBridge#36]
The current version of Matrix-EmailBridge uses an very old version (v 0.1.0 beta.2 versus current v.0.8.0) of mautrix-go lib (https://github.com/tulir/mautrix-go, listed as maunium.net/go/mautrix in the code).  As such, the code compiles but doesn't actually work on a the current matrix synapse server (v 1.25).  Best fix is to update the code of this project to make it compatible with the current version of mautrix-go lib.

**Comment by bendschs** [comment]
ok, so i guess this project will claimed to be dead if someone doesn‘t adjust the code (which i am not capable of).

cheers
bendsch

**Comment by JojiiOfficial** [comment]
Should be fixed with #38.
