### ISSUE TITLE
Documentaion

### ISSUE THREAD

**Issue by wuast94** [JojiiOfficial/Matrix-EmailBridge#39]
I try to get this up and running with docker. 
I have the cfg.json and edited it .. and thats the point were i stuck

what is the accesstoken and where do i get it? 
whats should the user id be? the mailbot user? the user that can controll the mailbot? 

how can i link the bridge to matrix? mautriy is using a registration.yaml.

are there any ports i have to open? 

i am very new to matrix and bridging and it would be great if the doku is more on a noob level to make it easier :) 

and i cant join #jojiiMail:matrix.jojii.de "M_UNKNOWN" was the error

**Comment by JojiiOfficial** [comment]
I updated the readme, it should be easier to follow now. Also #38 changed the way of authenticating. The JojiiMail matrix room does not exist anymore I removed that from the readme too. If there are further questions or issues regarding the descriptions, please reopen this issue.

**Comment by wuast94** [comment]
works now for me. was unclear that i have to create an extra user :)
