### ISSUE TITLE
bad parameter: password

### ISSUE THREAD

**Issue by bendschs** [JojiiOfficial/Matrix-EmailBridge#40]
getting the following when trying to run the bridge with latest matrix-synapse_

```
/emailbridge 
Logging into matrix.agreiter.ch as @emailbot:matrix.agreiter.ch
panic: failed to POST /_matrix/client/r0/login: M_INVALID_PARAM (HTTP 400): Bad parameter: password

goroutine 1 [running]:
main.loginMatrix()
	/opt/synapse/Matrix-EmailBridge/main/Main.go:100 +0x3ac
main.main()
	/opt/synapse/Matrix-EmailBridge/main/Main.go:885 +0x2d0
```

**Comment by JojiiOfficial** [comment]
Did you upgrade from an older version? Are you running the latest commit? Try to remove/rename the config file and let the bridge create a new one. Then fill out the values. Don't forget to use the bot-account password, not the accesstoken.

**Comment by bendschs** [comment]
thx, that was it ... regenerated the config, now it‘s working ...
