### ISSUE TITLE
Allow customization of the message sent to matrix

### ISSUE THREAD

**Issue by MacNokker** [JojiiOfficial/Matrix-EmailBridge#44]
I would like the message sent to the matrix room to be just the mail subject line.

Basically, to have a quick overview, if I should open my mail client.

Is that possible currently?

Cheers!

**Comment by JojiiOfficial** [comment]
This should be possible if you remove [this](https://github.com/JojiiOfficial/Matrix-EmailBridge/blob/master/main/Main.go#L1060) entire `if`-block and compile it again. Since I'm not working on this project anymore, I won't add such a feature.

**Comment by MacNokker** [comment]
Thanks, i had no idea this project wasn't ongoing anymore.
I've found a different solution: 
sieve rule -> shell script posting to matrix
